"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.
"""

import os
import sys
from dotenv import load_dotenv
from pathlib import Path


# ==================================================
# BASE DIRECTORY / ENVIRONMENT FILE
# ==================================================

BASE_DIR = Path(
    __file__
).resolve().parent.parent

load_dotenv(
    BASE_DIR / ".env"
)


# ==================================================
# APPLICATION ENVIRONMENT
# ==================================================

APP_ENV = (
    os.getenv(
        "APP_ENV",
        "development",
    )
    .strip()
    .lower()
)


if APP_ENV not in {
    "development",
    "production",
}:

    raise ValueError(
        "APP_ENV must be either "
        "'development' or 'production'."
    )


IS_PRODUCTION = (
    APP_ENV
    ==
    "production"
)


# ==================================================
# SECRET KEY
# ==================================================

SECRET_KEY = (
    os.getenv(
        "DJANGO_SECRET_KEY"
    )
)


if not SECRET_KEY:

    raise ValueError(
        "DJANGO_SECRET_KEY must be configured."
    )


# ==================================================
# APPLICATION BUILD INFORMATION
# ==================================================

APP_NAME = (
    os.getenv(
        "APP_NAME",
        "django-ims",
    )
    .strip()
)


APP_VERSION = (
    os.getenv(
        "APP_VERSION",
        "0.1.0",
    )
    .strip()
)


APP_BUILD = (
    os.getenv(
        "APP_BUILD",
        "development",
    )
    .strip()
)


GIT_COMMIT_SHA = (
    os.getenv(
        "GIT_COMMIT_SHA",
        "",
    )
    .strip()
)


if not APP_NAME:

    raise ValueError(
        "APP_NAME cannot be empty."
    )


if not APP_VERSION:

    raise ValueError(
        "APP_VERSION cannot be empty."
    )


if not APP_BUILD:

    raise ValueError(
        "APP_BUILD cannot be empty."
    )


# ==================================================
# DEBUG
# ==================================================

DEBUG = (
    os.getenv(
        "DJANGO_DEBUG",
        "FALSE",
    )
    .strip()
    .lower()
    ==
    "true"
)


if (
    IS_PRODUCTION
    and
    DEBUG
):

    raise ValueError(
        "DJANGO_DEBUG must be false "
        "when APP_ENV=production."
    )


# ==================================================
# ALLOWED HOSTS
# ==================================================

allowed_hosts_env = (
    os.getenv(
        "ALLOWED_HOSTS",
        "",
    )
    .strip()
)


if IS_PRODUCTION:

    ALLOWED_HOSTS = [
        host.strip()

        for host
        in allowed_hosts_env.split(",")

        if host.strip()
    ]

    if not ALLOWED_HOSTS:

        raise ValueError(
            "ALLOWED_HOSTS must be configured "
            "in production."
        )

    if "*" in ALLOWED_HOSTS:

        raise ValueError(
            "Wildcard ALLOWED_HOSTS is not "
            "allowed in production."
        )

else:

    ALLOWED_HOSTS = [
        "127.0.0.1",
        "localhost",
        "testserver",
    ]


# ==================================================
# CORS / FRONTEND ORIGINS
# ==================================================
#
# IMPORTANT:
# This must exist BEFORE CSRF_TRUSTED_ORIGINS,
# because CSRF configuration below uses it.
# ==================================================

FRONTEND_ORIGINS_RAW = (
    os.getenv(
        "FRONTEND_ORIGINS",
        (
            "http://localhost:3000,"
            "http://127.0.0.1:3000,"
            "http://localhost:8081,"
            "http://127.0.0.1:8081"
        ),
    )
    .strip()
)


FRONTEND_ORIGINS = [
    origin.strip().rstrip("/")

    for origin
    in FRONTEND_ORIGINS_RAW.split(",")

    if origin.strip()
]


if "*" in FRONTEND_ORIGINS:

    raise ValueError(
        "Wildcard frontend origins "
        "are not allowed."
    )


if IS_PRODUCTION:

    if not FRONTEND_ORIGINS:

        raise ValueError(
            "FRONTEND_ORIGINS must be "
            "configured in production."
        )

    for origin in FRONTEND_ORIGINS:

        if not origin.startswith(
            "https://"
        ):

            raise ValueError(
                "Production FRONTEND_ORIGINS "
                "must use https://"
            )


CORS_ALLOWED_ORIGINS = (
    FRONTEND_ORIGINS
)


CORS_ALLOW_CREDENTIALS = True


CORS_ALLOW_ALL_ORIGINS = False


CORS_EXPOSE_HEADERS = [
    "X-Request-ID",
    "X-Correlation-ID",
    "X-RateLimit-Limit",
    "X-RateLimit-Remaining",
    "X-RateLimit-Reset",
    "Retry-After",
]


CORS_PREFLIGHT_MAX_AGE = (
    60 * 60
)


# ==================================================
# CSRF TRUSTED ORIGINS
# ==================================================
#
# CORS and CSRF are separate protections.
#
# Production trusts only configured frontend origins.
#
# Development additionally trusts Django's local
# backend origins.
# ==================================================

if IS_PRODUCTION:

    CSRF_TRUSTED_ORIGINS = [
        *FRONTEND_ORIGINS,
    ]

else:

    CSRF_TRUSTED_ORIGINS = [
        "http://127.0.0.1:8000",
        "http://localhost:8000",

        *FRONTEND_ORIGINS,
    ]


# ==================================================
# APPLICATIONS
# ==================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # CORS
    "corsheaders",

    # IMS
    "apps.core.apps.CoreConfig",
    "apps.accounts.apps.AccountsConfig",
    "apps.organizations.apps.OrganizationsConfig",
    "apps.authorization.apps.AuthorizationConfig",
    "apps.products",
    "apps.inventory",
    "apps.purchasing",
    "apps.sales",
    "apps.finance",
]


# ==================================================
# MIDDLEWARE
# ==================================================

MIDDLEWARE = [
    # ==============================================
    # DJANGO SECURITY
    # ==============================================

    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    # ==============================================
    # CORS
    # Must run before CommonMiddleware.
    # ==============================================

    "corsheaders.middleware.CorsMiddleware",

    # ==============================================
    # IMS SECURITY RESPONSE HEADERS
    # ==============================================

    (
        "apps.core.middleware."
        "security_response_middleware."
        "SecurityResponseMiddleware"
    ),

    # ==============================================
    # SESSION
    # ==============================================

    "django.contrib.sessions.middleware.SessionMiddleware",

    # ==============================================
    # COMMON / CSRF
    # ==============================================

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    # ==============================================
    # DJANGO AUTH
    # ==============================================

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    # ==============================================
    # IMS MONGODB AUTH
    # ==============================================

    "apps.accounts.middleware.MongoAuthenticationMiddleware",

    # ==============================================
    # DJANGO MESSAGES
    # ==============================================

    "django.contrib.messages.middleware.MessageMiddleware",

    # ==============================================
    # FRAME PROTECTION
    # ==============================================

    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # ==============================================
    # REQUEST CORRELATION
    # ==============================================

    (
        "apps.core.middleware."
        "request_id_middleware."
        "RequestIDMiddleware"
    ),

    # ==============================================
    # EXCEPTION LOGGING
    # ==============================================

    (
        "apps.core.middleware."
        "exception_logging_middleware."
        "ExceptionLoggingMiddleware"
    ),

    # ==============================================
    # REQUEST / RESPONSE LOGGING
    # ==============================================

    (
        "apps.core.middleware."
        "request_logging_middleware."
        "RequestLoggingMiddleware"
    ),
]


# ==================================================
# URL / WSGI
# ==================================================

ROOT_URLCONF = (
    "config.urls"
)


WSGI_APPLICATION = (
    "config.wsgi.application"
)


# ==================================================
# TEMPLATES
# ==================================================

TEMPLATES = [
    {
        "BACKEND":
            "django.template.backends.django.DjangoTemplates",

        "DIRS":
            [],

        "APP_DIRS":
            True,

        "OPTIONS": {
            "context_processors": [
                (
                    "django.template."
                    "context_processors.request"
                ),

                (
                    "django.contrib.auth."
                    "context_processors.auth"
                ),

                (
                    "django.contrib.messages."
                    "context_processors.messages"
                ),
            ],
        },
    },
]


# ==================================================
# DATABASE
# ==================================================
#
# Django ORM is intentionally not used as the
# application's persistence layer.
#
# MongoDB + MongoEngine are configured separately.
# ==================================================

DATABASES = {
    "default": {
        "ENGINE":
            "django.db.backends.dummy",
    }
}


# ==================================================
# AUTHENTICATION BACKEND
# ==================================================

AUTHENTICATION_BACKENDS = [
    "apps.accounts.backends.MongoEngineBackend",
]


# ==================================================
# PASSWORD VALIDATION
# ==================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth."
            "password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },

    {
        "NAME": (
            "django.contrib.auth."
            "password_validation."
            "MinimumLengthValidator"
        ),
    },

    {
        "NAME": (
            "django.contrib.auth."
            "password_validation."
            "CommonPasswordValidator"
        ),
    },

    {
        "NAME": (
            "django.contrib.auth."
            "password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ==================================================
# INTERNATIONALIZATION
# ==================================================

LANGUAGE_CODE = (
    "en-us"
)


TIME_ZONE = (
    "UTC"
)


USE_I18N = True


USE_TZ = True


# ==================================================
# STATIC FILES
# ==================================================

STATIC_URL = (
    "/static/"
)


STATIC_ROOT = (
    BASE_DIR
    /
    "staticfiles"
)


# ==================================================
# STATIC FILE STORAGE
# ==================================================
#
# Development:
# Standard Django static-file storage.
#
# Production:
# WhiteNoise compressed + hashed static assets.
# ==================================================

if IS_PRODUCTION:

    STATICFILES_BACKEND = (
        "whitenoise.storage."
        "CompressedManifestStaticFilesStorage"
    )

else:

    STATICFILES_BACKEND = (
        "django.contrib.staticfiles.storage."
        "StaticFilesStorage"
    )


STORAGES = {
    "default": {
        "BACKEND": (
            "django.core.files.storage."
            "FileSystemStorage"
        ),
    },

    "staticfiles": {
        "BACKEND":
            STATICFILES_BACKEND,
    },
}


# ==================================================
# EMAIL CONFIGURATION
# ==================================================

EMAIL_MODE = (
    os.getenv(
        "EMAIL_MODE",
        "development",
    )
    .strip()
    .lower()
)


def env_bool(
    name,
    default=False,
):
    value = (
        os.getenv(
            name
        )
    )

    if value is None:

        return default

    return (
        value
        .strip()
        .lower()
        in {
            "1",
            "true",
            "yes",
            "on",
        }
    )


DEFAULT_FROM_EMAIL = (
    os.getenv(
        "DEFAULT_FROM_EMAIL",
        "no-reply@demoinventory.local",
    )
)


# ==================================================
# DEVELOPMENT EMAIL
# ==================================================

if EMAIL_MODE == "development":

    MAILERS = {
        "default": {
            "BACKEND": (
                "django.core.mail.backends."
                "locmem.EmailBackend"
            ),
        },
    }


# ==================================================
# PRODUCTION SMTP
# ==================================================

elif EMAIL_MODE == "production":

    SMTP_HOST = (
        os.getenv(
            "SMTP_HOST",
            "",
        )
        .strip()
    )


    SMTP_USERNAME = (
        os.getenv(
            "SMTP_USERNAME",
            "",
        )
        .strip()
    )


    SMTP_PASSWORD = (
        os.getenv(
            "SMTP_PASSWORD",
            "",
        )
    )


    try:

        SMTP_PORT = int(
            os.getenv(
                "SMTP_PORT",
                "587",
            )
        )

    except ValueError:

        raise ValueError(
            "SMTP_PORT must be an integer."
        )


    SMTP_USE_TLS = env_bool(
        "SMTP_USE_TLS",
        True,
    )


    SMTP_USE_SSL = env_bool(
        "SMTP_USE_SSL",
        False,
    )


    # ==============================================
    # VALIDATION
    # ==============================================

    if not SMTP_HOST:

        raise ValueError(
            "SMTP_HOST is required "
            "in production email mode."
        )


    if not SMTP_USERNAME:

        raise ValueError(
            "SMTP_USERNAME is required "
            "in production email mode."
        )


    if not SMTP_PASSWORD:

        raise ValueError(
            "SMTP_PASSWORD is required "
            "in production email mode."
        )


    if not DEFAULT_FROM_EMAIL:

        raise ValueError(
            "DEFAULT_FROM_EMAIL is required "
            "in production email mode."
        )


    if (
        SMTP_USE_TLS
        and
        SMTP_USE_SSL
    ):

        raise ValueError(
            "SMTP_USE_TLS and SMTP_USE_SSL "
            "cannot both be enabled."
        )


    MAILERS = {
        "default": {
            "BACKEND": (
                "django.core.mail.backends."
                "smtp.EmailBackend"
            ),

            "OPTIONS": {
                "host":
                    SMTP_HOST,

                "port":
                    SMTP_PORT,

                "username":
                    SMTP_USERNAME,

                "password":
                    SMTP_PASSWORD,

                "use_tls":
                    SMTP_USE_TLS,

                "use_ssl":
                    SMTP_USE_SSL,

                "timeout":
                    20,
            },
        },
    }


# ==================================================
# INVALID EMAIL MODE
# ==================================================

else:

    raise ValueError(
        "EMAIL_MODE must be either "
        "'development' or 'production'."
    )


# ==================================================
# SECURITY RESPONSE SETTINGS
# ==================================================

SECURE_CONTENT_TYPE_NOSNIFF = True


X_FRAME_OPTIONS = (
    "DENY"
)


SECURE_REFERRER_POLICY = (
    "strict-origin-when-cross-origin"
)


SECURE_CROSS_ORIGIN_OPENER_POLICY = (
    "same-origin"
)


# ==================================================
# ENVIRONMENT SECURITY
# ==================================================

if IS_PRODUCTION:

    SECURE_SSL_REDIRECT = True

    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SECURE = True

    SESSION_COOKIE_HTTPONLY = True

    CSRF_COOKIE_HTTPONLY = False

    SECURE_HSTS_SECONDS = (
        31536000
    )

    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

    SECURE_HSTS_PRELOAD = True

else:

    SECURE_SSL_REDIRECT = False

    SESSION_COOKIE_SECURE = False

    CSRF_COOKIE_SECURE = False

    SESSION_COOKIE_HTTPONLY = True

    CSRF_COOKIE_HTTPONLY = False

    SECURE_HSTS_SECONDS = 0

    SECURE_HSTS_INCLUDE_SUBDOMAINS = False

    SECURE_HSTS_PRELOAD = False


# ==================================================
# REVERSE PROXY / HTTPS
# ==================================================

TRUST_PROXY_SSL_HEADER = (
    os.getenv(
        "TRUST_PROXY_SSL_HEADER",
        "false",
    )
    .strip()
    .lower()
    in {
        "1",
        "true",
        "yes",
        "on",
    }
)


if (
    IS_PRODUCTION
    and
    TRUST_PROXY_SSL_HEADER
):

    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https",
    )

else:

    SECURE_PROXY_SSL_HEADER = None


# ==================================================
# SESSION SECURITY
# ==================================================

SESSION_ENGINE = (
    "apps.accounts.session_backend"
)


SESSION_COOKIE_NAME = (
    "ims_sessionid"
)


SESSION_COOKIE_HTTPONLY = True


SESSION_COOKIE_SAMESITE = (
    "Lax"
)


SESSION_SAVE_EVERY_REQUEST = True


SESSION_EXPIRE_AT_BROWSER_CLOSE = False


# 8 hours
SESSION_COOKIE_AGE = (
    60 * 60 * 8
)

# ==================================================
# CSRF COOKIE
# ==================================================

CSRF_FAILURE_VIEW = (
    "apps.core.csrf.csrf_failure"
)


CSRF_COOKIE_NAME = (
    "csrftoken"
)


CSRF_COOKIE_HTTPONLY = False


CSRF_COOKIE_SAMESITE = (
    SESSION_COOKIE_SAMESITE
)


CSRF_USE_SESSIONS = False
# ==================================================
# LOGGING
# ==================================================

LOG_LEVEL = (
    os.getenv(
        "DJANGO_LOG_LEVEL",
        "INFO",
    )
    .strip()
    .upper()
)


VALID_LOG_LEVELS = {
    "DEBUG",
    "INFO",
    "WARNING",
    "ERROR",
    "CRITICAL",
}


if LOG_LEVEL not in VALID_LOG_LEVELS:

    raise ValueError(
        "Invalid DJANGO_LOG_LEVEL."
    )


# ==================================================
# ENVIRONMENT LOG LEVEL POLICY
# ==================================================

LOG_LEVEL_ORDER = {
    "DEBUG": 10,
    "INFO": 20,
    "WARNING": 30,
    "ERROR": 40,
    "CRITICAL": 50,
}


if (
    IS_PRODUCTION
    and
    LOG_LEVEL_ORDER[
        LOG_LEVEL
    ]
    <
    LOG_LEVEL_ORDER[
        "INFO"
    ]
):

    raise ValueError(
        "Production DJANGO_LOG_LEVEL "
        "must be INFO or higher."
    )


# ==================================================
# THIRD-PARTY LOGGING
# ==================================================

THIRD_PARTY_LOG_LEVEL = (
    "WARNING"
)


# ==================================================
# DJANGO LOGGING CONFIGURATION
# ==================================================

LOGGING = {
    "version":
        1,

    "disable_existing_loggers":
        False,

    # ==============================================
    # FORMATTERS
    # ==============================================

    "formatters": {
        "standard": {
            "format": (
                "[{asctime}] "
                "{levelname} "
                "{name}: "
                "{message}"
            ),

            "style":
                "{",
        },
    },

    # ==============================================
    # HANDLERS
    # ==============================================

    "handlers": {
        "console": {
            "class":
                "logging.StreamHandler",

            "formatter":
                "standard",
        },
    },

    # ==============================================
    # ROOT LOGGER
    # ==============================================

    "root": {
        "handlers": [
            "console",
        ],

        "level":
            LOG_LEVEL,
    },

    # ==============================================
    # LOGGERS
    # ==============================================

    "loggers": {
        "django": {
            "handlers": [
                "console",
            ],

            "level":
                LOG_LEVEL,

            "propagate":
                False,
        },

        "ims": {
            "handlers": [
                "console",
            ],

            "level":
                LOG_LEVEL,

            "propagate":
                False,
        },

        "pymongo": {
            "handlers": [
                "console",
            ],

            "level":
                THIRD_PARTY_LOG_LEVEL,

            "propagate":
                False,
        },

        "mongoengine": {
            "handlers": [
                "console",
            ],

            "level":
                THIRD_PARTY_LOG_LEVEL,

            "propagate":
                False,
        },
    },
}


# ==================================================
# REQUEST PERFORMANCE
# ==================================================

try:

    SLOW_REQUEST_THRESHOLD_SECONDS = float(
        os.getenv(
            "SLOW_REQUEST_THRESHOLD_SECONDS",
            "2.0",
        )
    )

except ValueError:

    raise ValueError(
        "SLOW_REQUEST_THRESHOLD_SECONDS "
        "must be numeric."
    )


try:

    REQUEST_TIMEOUT_SECONDS = int(
        os.getenv(
            "REQUEST_TIMEOUT_SECONDS",
            "30",
        )
    )

except ValueError:

    raise ValueError(
        "REQUEST_TIMEOUT_SECONDS "
        "must be an integer."
    )


if SLOW_REQUEST_THRESHOLD_SECONDS <= 0:

    raise ValueError(
        "SLOW_REQUEST_THRESHOLD_SECONDS "
        "must be greater than zero."
    )


if REQUEST_TIMEOUT_SECONDS <= 0:

    raise ValueError(
        "REQUEST_TIMEOUT_SECONDS "
        "must be greater than zero."
    )


if (
    SLOW_REQUEST_THRESHOLD_SECONDS
    >=
    REQUEST_TIMEOUT_SECONDS
):

    raise ValueError(
        "Slow request threshold must be "
        "lower than request timeout."
    )


# ==================================================
# DEFAULT PRIMARY KEY
# ==================================================

DEFAULT_AUTO_FIELD = (
    "django.db.models.BigAutoField"
)


# ==================================================
# INTERNAL API TEST ENDPOINTS
# ==================================================

RUNNING_AUTOMATED_TESTS = (
    "test"
    in sys.argv
)


ENABLE_INTERNAL_API_TEST_ENDPOINTS = (
    RUNNING_AUTOMATED_TESTS
    or
    (
        not IS_PRODUCTION
        and
        os.getenv(
            "ENABLE_INTERNAL_API_TEST_ENDPOINTS",
            "false",
        )
        .strip()
        .lower()
        ==
        "true"
    )
)