import re
import uuid

from datetime import (
    datetime,
    timezone,
)


class RequestIDMiddleware:

    CLIENT_CORRELATION_HEADER = (
        "HTTP_X_CORRELATION_ID"
    )

    REQUEST_ID_RESPONSE_HEADER = (
        "X-Request-ID"
    )

    CORRELATION_RESPONSE_HEADER = (
        "X-Correlation-ID"
    )

    CORRELATION_ID_PATTERN = re.compile(
        r"^[A-Za-z0-9._:-]{8,100}$"
    )

    def __init__(
        self,
        get_response,
    ):
        self.get_response = (
            get_response
        )

    @classmethod
    def _normalize_correlation_id(
        cls,
        correlation_id,
    ):
        if not correlation_id:
            return None

        correlation_id = str(
            correlation_id
        ).strip()

        if not (
            cls.CORRELATION_ID_PATTERN
            .fullmatch(
                correlation_id
            )
        ):

            return None

        return correlation_id

    @staticmethod
    def _generate_request_id():
        return uuid.uuid4().hex

    def __call__(
        self,
        request,
    ):
        # ==================================================
        # SERVER REQUEST ID
        #
        # Always generated by the backend.
        # Never trust a client-supplied request ID.
        # ==================================================

        request_id = (
            self._generate_request_id()
        )

        # ==================================================
        # OPTIONAL CLIENT CORRELATION ID
        # ==================================================

        incoming_correlation_id = (
            request.META.get(
                self.CLIENT_CORRELATION_HEADER
            )
        )

        client_correlation_id = (
            self._normalize_correlation_id(
                incoming_correlation_id
            )
        )

        # ==================================================
        # REQUEST CONTEXT
        # ==================================================

        request.request_id = (
            request_id
        )

        request.client_correlation_id = (
            client_correlation_id
        )

        request.request_received_at = (
            datetime.now(
                timezone.utc
            )
        )

        # ==================================================
        # RESPONSE
        # ==================================================

        response = self.get_response(
            request
        )

        response[
            self.REQUEST_ID_RESPONSE_HEADER
        ] = request_id

        if client_correlation_id:

            response[
                self.CORRELATION_RESPONSE_HEADER
            ] = client_correlation_id

        return response